# Generated by Django 4.2.7 on 2023-11-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="/profile_default.png",
                upload_to="profile_pictures/",
            ),
        ),
    ]
