# Generated by Django 4.2.7 on 2023-11-21 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="id",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="uuid",
            field=models.TextField(
                default=1, max_length=36, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
