#TODO: Maybe update to a most recent version
version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start
        volumes:
            # Map current directory to working directory in our container
            # Changes in local directory will be reflected in container
            # :z is used to apply a SELinux label for proper access control
            - .:/app:z
        ports:
            -  "8000:8000"
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - postgres
        networks:
            - blogs-api

    postgres:
        build:
            context: .
            dockerfile: ./docker/local/postgres/Dockerfile
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
        env_file:
            - ./.envs/.local/.postgres
        networks:
            - blogs-api

networks:
    blogs-api:
        driver: bridge

volumes:
    local_postgres_data: {}